import { JsonSchemaType, ToolCallType } from '$lib/enums';
import type { OpenAIToolDefinition } from '$lib/types';

export const RENDER_SVG_TOOL_NAME = 'render_svg';

export const SVG_OUTPUT_MAX_BYTES = 512_000;

export const SVG_EMPTY_OUTPUT = '(no SVG output)';

export const SVG_TRUNCATION_NOTICE = '[output truncated]';

export const RENDER_SVG_TOOL_DEFINITION: OpenAIToolDefinition = {
	type: ToolCallType.FUNCTION,
	function: {
		name: RENDER_SVG_TOOL_NAME,
		description:
			'Embed SVG content in the chat. Accepts raw SVG markup (optionally generated by D3 or similar libraries). Content is sanitized for safety before rendering.',
		parameters: {
			type: JsonSchemaType.OBJECT,
			properties: {
				svg: {
					type: JsonSchemaType.STRING,
					description: 'SVG markup to render'
				},
				title: {
					type: JsonSchemaType.STRING,
					description: 'Optional title for the visualization'
				}
			},
			required: ['svg']
		}
	}
};
